kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "StructuredAuthenticationConfiguration": true
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            authentication-config: /etc/kubernetes/authentication-config.yaml
          extraVolumes:
            - name: authentication-config
              hostPath: /etc/kubernetes/authentication-config.yaml
              mountPath: /etc/kubernetes/authentication-config.yaml
              readOnly: true
              pathType: File
    extraMounts:
      - hostPath: /Users/vsurzhyk/src/Mirantis/2A-test/k0rdent-gitops/sso/authentication-config.yaml
        containerPath: /etc/kubernetes/authentication-config.yaml
        readOnly: true
