apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://localhost:8080
  oidc.config: |
    name: Okta
    issuer: "https://trial-6424061.okta.com/oauth2/ausqbdpmlgOuS1opH697"
    clientID: 0oaqbdpjf3GOrVklP697
    skipAudienceCheckWhenTokenHasNoAudience: true
    requestedScopes: ["openid", "profile", "email"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
    enablePKCEAuthentication: true
