apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-cluster-identity-secret
  namespace: kcm-system
spec:
  encryptedData:
    AccessKeyID: AgCN5G6C+X8x3RtwMZhHU4ziHWDnglw7CN05OXkIuN+allwa3SjxDPZLZQylvCgEbUfFZbVF9XOFrhiaGhJ7pCKrBOgwgTLk3NzTdu0v4R9RyfJukShXU9HfldBWvGhxBxEiE0PHfo3LhGKQeANj9/8BB2Z5HEveDuM+nR2lwWluXw8Drr92SFH0TrHMZ1CRhm7yRU8/8gUYJx5ql0CFkb8fLa0SMUnayvYBj428HgkyqY56zkubcloUCvWWMQIhbgt1hwXre4HgkSGONFPGRj7bAZe/wsQDzscMUD8vtc8cuOSszc48VTnMigwkS4rlfzvuSJFEEI1cMyO9y0gnBCfzGVstUGeZn+ToESeXbFsQAjvCG9TBLZnr5+ALd7k/bz4G3z1hvTcDsQ+O45+2JtqNJXIvjRjV6Pg0Qzys1Se+ECvILQUA05fkgQXQTF0QbEdG9FOY5PbWT5/TaYbMbWe+1mt92xZW9zRxv8uvxrHuSmsf0zXsi61BBHjZzEYXg+inImVT8Vv1UvzxPay7NHhUQMTBMWc9Kn9nKCnMdrLcTECqXcYO0vHAx6Q3W32fDIp23S3byaSLO6PrntvOKLonG0fR2afQ01i8Mv2Qvd+LpfQrjyKHiNRCzERw32IgH0XaTX089CVm1pcx/MAO1E1PZ55DkNopEd1N9D76nGL+TzGllC4qxlyg3g8ToSxd/jBNmhsmeercjMtK7Eh67bW22KXx1A==
    SecretAccessKey: AgBRBYxR84QIJsiDapTuRSeGY4pI6UZKLbS988Ohc9aZ8EIIuWoE8hqqZBQobfycoh6UlFAUUmkeRlQosy0xZ8UPK0lsmUh2dkfQ9F03ZqzSK1L/IPR0ZAxAXFygfvQ8/0EtLyx/h+th+ZQhj8XpLS0Gkwzj2dxUdQHC4NAorRFUU+rbD6AdK7JOzHfaILQ3xdnCPKiMs9SLIeuIq/WppillxHb3NVNVcLQNZ3N5dP+nLSDb+L0xkhyBowV7wRqUFj2U76qO6uma0KSWBmwkM80csaAf/4P+j2bsuUlB1N6hhaAxIOKyhpA1c+5MXgFxfk9y5UaOK9Nq6mLgeThXzZC8eMjRb89bADmX8d00l5tY+9OPUFF+KaFYGjESa10hjK9Z9RZdC/+Zn61VrDVsVYEWwW0MAetOKpmiqh+hDw+o0f/+OUdOLRsxTWuYUHHXXa1H705LqON2HfrLe88tgpuHqdCt5QARp9A591nv52DGPJkwJgzFPYf9RfvXK87/tImR8vfqkNrQfG6dVQRFVoGK6J11IU7jeKt2gw2EDaJ2SQjvPAlXvkTbb5F+wmneACVZCwWmzkqwgjLfxBnK5cyBDJCBNqGTqmpHsiLKnc5jJ4Zn9SPXdFnl/Tbk/fpiJ/zyUqPwgmdh89epHO2hjNlScdf+qI0Upda2r2QSyUGth7rdD1b0d6hQvgFhsAmVeJUR3v88lX6XqD9wJTsdZY6VK4UNKTr7cOkisUG9wvVmrPDTa/MyVJJd
  template:
    metadata:
      creationTimestamp: null
      name: aws-cluster-identity-secret
      namespace: kcm-system
    type: Opaque
