---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openstack-cloud-config
  namespace: kcm-system
spec:
  encryptedData:
    clouds.yaml: AgAsKuScLJeYM5Smv8AY+7WmJbD5sk4y34dFoOlfeXXuUXlblyEpC7Ndat7bp6LJ1JW3DTH+bmcHXxXuY54TXO4HQeUteqvQIZuxP3GKc6L1XiB5G94PoIbhO1sTWGrbSlytD7ibzCJIYs8UNVoJ8M3s0LZckSuuRvciypAmYcSnORfIHReGlsBfueaAs+kSguj3zQCH1IN/pWJIYl6WlJTGVnMEctfLXWLePSAwZvN0FPm7rQgZfop7yfSB3lQVWblM6+GKYp8/5Hj9okOUItsr1FXWG2r2HJsTL+Uadtum56PZSAAPVlyIoaGKIrvtss0QCYNkVbcKYCdO6KiiNNmAIA2sfS/QvI+b7qBrT6ZU3Fx6QMiUAM+/X1qa0oD7nzfNmVkCPdW5zRB/3AqzwRvxrUYJ60AnFK17gM+l6w/zyqee1PB84B5bLM0xnhnm63cL9ZMGGHE4bguAZMKQHcoLORyYcHpJqqWiof3wwI09x3vF7gHPiuYkRiUScUdCZ5zHdeuLjj3izLwfJXNTOgdx7v7rMHx/rVszoaTuPdlY/mo1fkntlYg5CSM4VEwjXgGieTI9QbuHIMqMSzdTVvnLZ+cMkKXsQRrLIeqD5VeCLOH7gY3O7HQ+PhwEL1ao/NqVY8ZdVi2Z0R6mwgeDfdmbnlM4zV/SZHjtNQZf3Bb17zbTPSOIcF4IXYaHJpOtUR+efkze461a73ReeKHGu3elX73QdISqCv+PbaSfL/RXNfAh7VvipNikRA2jam5lJXLuhgTwoWTSiyUWBiW7OVKJp4CBbd4NatGacUcqQXccKndxxZBYOrwqI6MFE4YOuDsCqM29fjgQegLyiZGOTeBezlFXILCvsWgvRxO3oSWTBqADBawlcOCNf263mDhjhphX5j/2gmo7/dMLq9BOgYvgcjOjQqGiqdnh8vCqoelIto89BX0itpW5Vb/W4PrkHFBgSlhs5ncubsVuT59OUdfOfGKa8GM23HU9H+15EfKkuwoSSSQQprWQjCc3PTDz36By44nWmiRQSF7JvrMnf5JmGRSrVnhLQxry1mjaVtO4fvKYaJuJWuCEAhCJKm1wt/P+2Kf39M0wlHDIL0r7puE0sQWBWEozxtL2uL6DhLcZ5ER3dI3oi+YCThA8fXv5gQrpLZukGDK6SlNvVt/q6r5S0NTEMeHt2EGKCAQa9nLTL8BtmfcYRXKjJSpfV6oro/LsFhHyJovL+PkUTTRXWJFQ+YPqJA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        k0rdent.mirantis.com/component: kcm
      name: openstack-cloud-config
      namespace: kcm-system
