---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openstack-cloud-config
  namespace: dev
spec:
  encryptedData:
    clouds.yaml: AgAfRfbJjBUYZvMoy8prPCqeL5/tT3yg0hq/OLVuVFbzkUYGZ8ftPqPAy+ROZBnRdWJ5GHkL/7f4x8K4pbBSjkuEOVDzVLwnKv4NkVhRCrrXk0ytXPyDFFw7p9S4++nepolR3Ax2bLL5wFvnaoNliObOAoPeItLkrT6EhMIrva+1Ka7R01EsAdR/N8ZFMHvV7yQf3TkCJwb5zfDl2O0uqLBGx8znZ1w94N5ZksLW4TQ4YsKNAJRgcKTK7/GS3wzvRuzUQGF96cvIgS1G9f9HRsK0zrou1omL5/UEppSml6OecQlyGBTylXnUF8T1Jti8D+kocID+JGRK9eC28E6NVH224N7qEn3/xo9/pqe3VuZ1YwOeQIK9tQUEJ9bATRyUkAg+Q4PLKKWlQQFIGGNNfTNs37ZIZtoMCirI7tMK4mU3qZFVpV4+OZpbmGl2AtxV9djjJM3tr/g3IWDGNi1F05XdlyWDToDJkPLe2e2OU6+Y76rdL1s8VH/XcUOhOaNfdmm6c7+e4fTlWqThvfZ1H4Fqqpi0AgLWCeJ/gX331bR11CdBPwkPEvkNOoOYi+BybsYPtehyBcIcRnEbE3FNJPnKwQYulr2v/m/xHada24td3XlTiq74XvHnThH3jCjDdPWZYpdCrtRP/KuEs87Hz0hemNQlDakiMTL8shm5FT/7PZgTUO+FlKo1ciqvS/DkNSSRxYGmT+ZtyDaYG8ye1b2SNAupAibIXZtEYpCogEcHd7qpEdNYv3jPTFfobcocTZPeYZ2FiBNIhEmwCrG5DW9E4nPsclQnTCcGHakc5Sai/sgnG2iqHLBT+rbGYUKT4+AIaMmZt/bf4gKKTxa+4ppC7bRwAPjgZj5yGj9yRhO3aAkkQm7SRkqkl3dJhZReZ1Ot7/4a2j1OJB6lq/3eS5SpRVfwPLQLc9IVw0+kbmwKOzzuQbxMBX+AfoTwxHPPeuxCe7jLYIR5RhmL6BECOjDWUoYHdgIy3kPsBRTTuWwWZLu0S0q4bFGZrn5qE8oQdXKoeHsxz9MdRL4oyCssPTUqYlRjxC0ySTHrFFegInj6635BD59fA7n4r2RZjhvs4i14VmKXQ5MjhNNpLOogtoAPRBf917Mxfs+QwG7H10lciG9TqHtBHBYh/SO29YtDlUpo3dJAtQU1R5wDO2oX1VixJ3CK2RW2UfxMqQaU0qCRHS7+KoB4PHzf5J4tH3hXxocRr0dMvg949SrHxWrXreuVElYO3A==
  template:
    metadata:
      creationTimestamp: null
      name: openstack-cloud-config
      namespace: dev
