apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-dev
  namespace: argocd
spec:
  destination:
    namespace: kcm-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/dev
    repoURL: https://github.com/ironreality/k0rdent-gitops
