apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-config
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: management/kcm
    repoURL: https://github.com/ironreality/k0rdent-gitops
