---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openstack-cloud-config
  namespace: dev
spec:
  encryptedData:
    clouds.yaml: AgCJR3vZdpa/aESN2Jq4ekquWVw0GpWm6/9zeAuKR5XyVsK8OZ9caux10qEFIxuHoCq91f27Ih6v6yktKGUTMxzTm+HKKrsdL31PZ9f1oypoEv5O2X/E7I5tjet2tBc1lgIlaXRhyEHVkbdJfDaJyq1DpgE+mP+MThJDXTmdQWm3KLlQbfjx4y/4arno241z9KPRUKDoyrFSybizaCEaFUoYosKcEzXMC/uB44oAUIkgWz75uVLzKhTSBx6jtQhxhAyqtFrT4oXebSH1DLDXK6oKjwk4tRvsFoibq/zWR7RnbKB79byGi0zcwDB2KrD4NIzAxBvwCmGtmTnnvXjNnXuQbTuXrWdL8CBJKt4tSUijfp4YGcjUKd1+gVBiiSit2iLtHhYPJQ7Os6mfs7vqSBGCNSbStjJPFYdHXLkCRXbu4evN9Sayl5PeAyYxqi1LYsF4oe9dm4sAAInBrjS55CljNET1T+hglo4ZEbWz5WUJSOyf1YSy777qVPHpd8wL6odwi5wn8ouDFvYVpO03gJY9FoppbYS0yMP5EhWngLhQ5aH1F7jBpGmO5N+YjK+FKovPnVcTiQJg0u/X/p/09WdEDOyHj8S05Of5MoNv9d3Uqe9WJG7pgAty/RqPCrCLWR4NAHsoI+BPNV8Eki1GmHELIRhsGlIQtv/8ZHhR7rd/ebHRjm0gGH8OICDNk50ilXRCYTmkC5/REtqp26qtAmLgJaN6/04y3Iun5I/vc7ZwkYabRA0Y1YPfIWgwY49SSg6c6OM0EgVZRllJ8H2sObBEZApCfAFHmVfiSgbDRgQXAc0jyS5Rp75M5+Msoo/kgL5EKEn9pEa9n1JQZxuVAbh1yqao1MpJceLqQwfnwReqZne+S/9tCi3sbxaZhWsvsSOVFTbnK2Izn16hO3yUFuFMAYbsxSVViVwbELsO0RZ2WMGehUKm+mdvKRcJE+fzUGizfqX1XVi9s9Har0yta8FIHqHY+Fu16c6BxPDk6We3PtFRa4kV16D4DZtU+p65bJHsVDXwZYQCXDsGpwy1rshaoGW5Qn4dOw7PdtPy9k1d1HMvl6OPnrqOcPDvGaik08mGYbTm5GNuJ4XoSHFEs0ozYGEfZnhDctniXxdJrGTzcEWLeYNo/jijDv0Tga9BVSnkTD1YGZG9CLFoIYCXfwTb0Ads3P72e6wur2Fz6VojWAW6KS5YSNfjYMrY/sHqfF1hiruUSfJ1wBq8vwaBTXmgiDXfHg==
  template:
    metadata:
      creationTimestamp: null
      name: openstack-cloud-config
      namespace: dev
