apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-secrets
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: credentials/dev
    repoURL: openstack-standalone-cp-0-2-0
