apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/ironreality/k0rdent-gitops
status: {}
