apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: credentials/dev
    repoURL: https://github.com/ironreality/k0rdent-gitops
