apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: vsurzhyk-aws-managed-dev-1
  namespace: dev
spec:
  template: aws-standalone-cp-0-2-0
  credential: aws-cluster-identity-cred
  config:
    controlPlaneNumber: 1
    workersNumber: 1
    region: eu-central-1
    controlPlane:
      instanceType: t3.medium
    worker:
      instanceType: t3.medium
