apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: my-test-1
  namespace: dev
spec:
  template: openstack-standalone-cp-0-2-0
  credential: os-cluster-identity-cred
  config:
    clusterLabels:
      env: dev
    authURL: https://keystone.ic-eu.ssl.mirantis.net/
    externalNetwork:
      filter:
        name: public
    controlPlaneNumber: 3
    workersNumber: 1
    controlPlane:
      flavor: system.compact.openstack.telemetry
      image:
        filter:
          name: ubuntu-24.04-x86_64
      sshPublicKey: heiko
    worker:
      flavor: system.compact.openstack.telemetry
      image:
        filter:
          name: ubuntu-24.04-x86_64
      sshPublicKey: heiko
    identityRef:
      name: openstack-cloud-config
      cloudName: openstack
      region: RegionOne
