apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  labels:
    k0rdent.mirantis.com/component: kcm
  name: dex-0-19-1
  namespace: kcm-system
spec:
  helm:
    chartSpec:
      chart: dex
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: catalog-core
      version: 0.19.1
