apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  labels:
    k0rdent.mirantis.com/component: kcm
  name: ingress-nginx-4-11-3
  namespace: kcm-system
spec:
  helm:
    chartSpec:
      chart: ingress-nginx
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: catalog-core
      version: 4.11.3
