apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: catalog-core
  namespace: kcm-system
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  labels:
    k0rdent.mirantis.com/managed: "true"
spec:
  insecure: true
  interval: 10m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/k0rdent/catalog/charts
